// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RapidCase.BasicSystem.Specifications.Setup
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class InitialSetUpFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "InitalSetup.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Initial set up", "When I start up a system from scratch the system will ask me for some information" +
                    " as database location and administration password", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Initial set up")))
            {
                RapidCase.BasicSystem.Specifications.Setup.InitialSetUpFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Show database location selection screen if database location is missing")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Initial set up")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void ShowDatabaseLocationSelectionScreenIfDatabaseLocationIsMissing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show database location selection screen if database location is missing", new string[] {
                        "web"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I start up the system for the first time");
#line 7
 testRunner.And("the database location is not set");
#line 8
 testRunner.When("I navigate to the default page");
#line 9
 testRunner.Then("I will be asked to enter the location of the database. Either I can select local " +
                    "and port number or a remote url and a port number.");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Select local machine as database location")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Initial set up")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void SelectLocalMachineAsDatabaseLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Select local machine as database location", new string[] {
                        "web"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I start up the system for the first time");
#line 14
 testRunner.And("database location selection screen i showing");
#line 15
 testRunner.When("I select local machine as database location, port 8080 as port and clicked save b" +
                    "utton");
#line 16
 testRunner.Then("the database location i saved as http://localhost:8080");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Select remote machine as database location")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Initial set up")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void SelectRemoteMachineAsDatabaseLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Select remote machine as database location", new string[] {
                        "web"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("I start up the system for the first time");
#line 21
 testRunner.And("database location selection screen i showing");
#line 22
 testRunner.When("I select that my database is on a remote machine. I enter 127.0.0.1 as database l" +
                    "ocation, port 8080 as port and clicked save button");
#line 23
 testRunner.Then("the database location i saved as http://127.0.0.1:8080");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Request password for administrator if it do not exist")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Initial set up")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void RequestPasswordForAdministratorIfItDoNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Request password for administrator if it do not exist", new string[] {
                        "web"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("Administrator do not have a password");
#line 28
 testRunner.When("I navigate to the default page");
#line 29
 testRunner.Then("I be shown a password field to enter a new password and a button to submit it");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Enter a new password for the administrator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Initial set up")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void EnterANewPasswordForTheAdministrator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enter a new password for the administrator", new string[] {
                        "web"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("Administrator do not have a password");
#line 34
 testRunner.And("I have navigated to the default page");
#line 35
 testRunner.And("I am requested to enter a password for the administrator");
#line 36
 testRunner.When("I enter test123 as password and click the submit button");
#line 37
 testRunner.Then("test123 will be saved as the password for the administrator and navigated to Rapi" +
                    "dCase Development Studio");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
